name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  lottie: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  date_picker_timeline: ^1.2.6
 

 
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Animation - 1747303886989.json
    - assets/images/avatar.jpeg
    - assets/images/abdelrahman.jpg
    
  fonts:
    - family: poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

